name: print_Cycle_s3
 
on: push
            
jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      cycle_key: ${{ steps.set-matrix.outputs.cycle_key }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install 
      - name: transform input
        id: transformInput
        uses: ./.github/actions/transform/
        with:
          cycle_key: 'XXX-1111,XXX-2222'
      - id: set-matrix
        run: |
          echo "::set-output name=cycle_key::${{ steps.transformInput.outputs.cycle_key }}"
  print:
    needs: pre
    runs-on: ubuntu-latest
    name: "${{ matrix.CYCLE_KEY }}"
    strategy:
      fail-fast: false
      matrix:
        CYCLE_KEY: ${{fromJSON( needs.pre.outputs.cycle_key )}}
    env:
      # CYCLE_KEY: ${{ inputs.cycle_key }}
      ENV_KEY: string
      VUS: 1
      DURATION: 'off'
      ITERATIONS: 1
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install 

      - name: Run Print
        if: always()
        run: node script.js cycleKey=${{ matrix.CYCLE_KEY }}