name: print_Cycle
 
on:
  workflow_dispatch:
    inputs:
      CYCLE_KEY:
        description: " Сycle key "
        required: true
        default: 'EEE-1111,EEE-2222'
      env_key:
        type: choice
        description: Environment
        options: 
        - staging
        - dev
      vus:
        description: " VUS "
        required: true
        default: 1
        type: number
      durationsOrIterations:
        type: choice
        description: " Durations or Iterations "
        options: 
        - iterations
        - durations
      # znach:
      #   description: " Введите значение ${{ fromJSON( github.event.inputs.durationsOrIterations )}} параметра "
      #   required: false
      #   type: number
      znach:
        # description: " Введите значение предыдущего параметра:\n
        # - если выбрали iterations укажите желаемое значение итераций        \n           
        # - если выбрали durations укажите значение в секундах "
        description: |-
          Введите значение предыдущего параметра:
          - если выбрали iterations укажите желаемое значение итераций
          - если выбрали durations укажите значение в секундах
        required: false
        default: 1
        type: number
            

      # durations:
      #   description: " Durations "
      #   required: true
      #   type: int

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      cycle_key: ${{ steps.set-matrix.outputs.cycle_key }}
    # env:
    #   # CYCLE_KEY: ${{ inputs.cycle_key }}
    #   ENV_KEY: ${{ inputs.env_key }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install 
      - name: transform input
        id: transformInput
        uses: ./.github/actions/transform/
        with:
          cycle_key: ${{ github.event.inputs.CYCLE_KEY }}
      - id: set-matrix
        run: |
          echo "::set-output name=cycle_key::${{ steps.transformInput.outputs.cycle_key }}"

  print:
    needs: pre
    runs-on: ubuntu-latest
    name: "${{ matrix.CYCLE_KEY }}"
    strategy:
      fail-fast: false
      matrix:
        CYCLE_KEY: ${{fromJSON( needs.pre.outputs.cycle_key )}}
    env:
      # CYCLE_KEY: ${{ inputs.cycle_key }}
      ENV_KEY: ${{ inputs.env_key }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install 

      - name: Run Print
        if: always()
        run: node script.js cycleKey=${{ matrix.CYCLE_KEY }} envKey=$ENV_KEY
        # run: node script.js cycleKey=$CYCLE_KEY envKey=$ENV_KEY