name: print_Cycle
 
on:
  pull_request:
    branches:
      - stage

jobs:
  print:
    runs-on: ubuntu-latest
    
    # env:
    #   CYCLE_KEY: ${{ inputs.cycle_key }}
    #   ENV_KEY: ${{ inputs.name }}
    #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #   TEST_VAR: ${{ secrets.TEST_VAR }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install 

      - name: Run Print
        if: always()
        run: node script.js

      - name: Update PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.BOT_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `URAAA!!!`
            });
