name: print_Cycle
 
on:
  pull_request:
    branches:
      - stage

jobs:
  print:
    runs-on: ubuntu-latest
    
    # env:
    #   CYCLE_KEY: ${{ inputs.cycle_key }}
    #   ENV_KEY: ${{ inputs.name }}
    #   ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #   TEST_VAR: ${{ secrets.TEST_VAR }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install 

      - name: Run Print
        if: always()
        run: node script.js

      - name: Update PR
        # if: github.event.pull_request
        - uses: actions/github-script@v5
        with:
          # github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const output = `
              You can find a link to the downloadable Cucumber Report below.

              | Name            | Link                                                                                                     |
              | --------------- | -------------------------------------------------------------------------------------------------------- |
              | Commit          | ${{ github.event.pull_request.head.sha }}                                                                |
              | Cucumber Report | [Download Artifact](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |

              Please note that files only stay for around 5 days!
              `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });




        # uses: actions/github-script@v6
        # id: plan-comment
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   script: |
        #     // 1. Retrieve existing bot comments for the PR
        #     const { data: comments } = await github.rest.issues.listComments({
        #       owner: context.repo.owner,
        #       repo: context.repo.repo,
        #       issue_number: context.issue.number,
        #     });

        #     # // 2. Find PR Comment
        #     # const botComment = comments.find(comment => {
        #     #   return comment.user.type === 'Bot' && comment.body.includes('Cucumber Report')
        #     # });

        #     // 3. Delete previous comment so PR timeline makes sense
        #     const output = `![badge]
        #        You can find a link to the downloadable Cucumber Report below.

        #        | Name            | Link                                                                                                     |
        #        | --------------- | -------------------------------------------------------------------------------------------------------- |
        #        | Commit          | ${{ github.event.pull_request.head.sha }}                                                                |
        #        | Cucumber Report | [Download Artifact](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) |

        #        Please note that files only stay for around 5 days!

        #        [badge]: https://img.shields.io/badge/Cucumber_Report!-23D96C?logo=cucumber&logoColor=fff&style=for-the-badge&labelColor=3fb950
        #        `;

        #     github.rest.issues.createComment({
        #       issue_number: context.issue.number,
        #       owner: context.repo.owner,
        #       repo: context.repo.repo,
        #       body: output
        #     });

        #     # if (botComment) {
        #     #   github.rest.issues.deleteComment({
        #     #     owner: context.repo.owner,
        #     #     repo: context.repo.repo,
        #     #     comment_id: botComment.id,
        #     #   });
        #     # }