name: Print Hello World Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' # Запускать каждые 5 минут

jobs:
  print_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, world!"